# Site settings
title: Dav Vendator IO
description: 'My personal space.'
url: 'https://dav-vendator.github.io'
baseurl: ''
# google_analytics: 
# disqus_shortname: 

author:
  name: 'Dav Vendator'
  email: er.singh.davinder.io@gmail.compressed
  twitter_username: '@DavVendator'
  facebook_username: dvendator
  github_username:  dav-vendator
  linkedin_username:  davvendator

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
